#!/usr/bin/env python3
"""Config writer used by `inboard init`. Loads a base YAML (the example, or an existing config), applies
dotted --set overrides and an optional --accounts JSON list, and writes the result. Used twice by init:
once to seed identity + accounts, once to write back the ids create_board.py returns.

    apply_config.py --base inboard.config.example.yaml --out inboard.config.yaml \
        --set identity.name="Ada" --set identity.timezone="Europe/London" \
        --accounts '[{"id":"personal","label":"Personal","provider":"gmail","address":"a@b.com","calendar":true}]'
"""
import argparse
import json
import sys

import yaml


def set_path(d, path, value):
    parts = path.split(".")
    for p in parts[:-1]:
        d = d.setdefault(p, {})
    d[parts[-1]] = value


def coerce(v):
    low = v.lower()
    if low in ("true", "false"):
        return low == "true"
    if low in ("null", "none", ""):
        return ""
    try:
        return int(v)
    except ValueError:
        return v


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--set", dest="sets", action="append", default=[])
    ap.add_argument("--accounts", default=None)
    a = ap.parse_args()

    with open(a.base) as f:
        cfg = yaml.safe_load(f) or {}

    for kv in a.sets:
        if "=" not in kv:
            sys.exit(f"apply_config: bad --set '{kv}' (want key.path=value)")
        k, v = kv.split("=", 1)
        set_path(cfg, k.strip(), coerce(v))

    if a.accounts is not None:
        cfg["accounts"] = json.loads(a.accounts)

    with open(a.out, "w") as f:
        f.write("# inboard configuration — generated by `inboard init`. See inboard.config.example.yaml for docs.\n")
        yaml.safe_dump(cfg, f, sort_keys=False, allow_unicode=True, default_flow_style=False)
    print("wrote", a.out)


if __name__ == "__main__":
    main()
